# Generated by Django 4.2.5 on 2023-10-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hierarchical", "0002_category_level_category_lft_category_rght_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="level",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="lft",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="rght",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
